version: '3'  
services:  
 db:  
   image: mariadb:latest  
   command: --wait_timeout=1800  
   environment:  
     MYSQL_TCP_PORT: 3306  
     MYSQL_ROOT_PASSWORD: mydbpass  
     MYSQL_DATABASE: nettailor_database  
     MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci  
     MYSQL_CHARACTER_SET_SERVER: utf8mb4  
     MYSQL_INIT_CONNECT: 'SET @@GLOBAL.max_allowed_packet=64_1024_1024;'  
   volumes:  
     - /home/user/wait/nettailor/sql:/var/lib/mysql  
   ports:  
     - "3306:3306"  
   restart: always  
 nettailor:  
   image: 3rtdevops/nettailor:latest  
   ports:  
   # Web Port  
     - "8040:8040"  
   # SSH Port  
     - "2222:2222"  
   environment:  
     # Basic Server Info  
     HOSTNAME: localhost  
     API_SERVER_PORT: 8032  
     # Default Admin User Information  
     USERNAME: myuser
     PASSWORD: myloginpass
     FULLNAME: Nettailor Admin  
     EMAIL: my@email.com  
     # Database Vars  
     DB_TYPE: mysql  
     DB_HOST: db  
     DB_PORT: 3306  
     DB_USER: root  
     DB_PASSWORD: mydbpass  
     DB_NAME: nettailor_database  
     # Image/Audio Proxy Vars  
     PROXY_PROTOCOL: http  
     NETTAILOR_PORT: 8040  
     USE_CLOUD_STORAGE: "False"  
     REVERSE_PROXY: "False"  
     # Enable or Disable Debug Mode for additional Printing  
     DEBUG_MODE: True  
   volumes:  
   # Mount the download location on the server if you want to. You could mount a nas to this folder or something like that  
     - /home/user/nettailor/backups:/opt/nettailor/backups  
     - /home/user/nettailor/configs:/opt/nettailor/configs  
     - /home/user/wait/nettailor/configs/clients_list.json:/opt/nettailor/clients_list.json
   depends_on:  
     - db
