[package]
name = "web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#trunk = "0.18.0"
#yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
yew = { version = "0.21.0", features = ["csr"] }
#yew = { "0.21.0", features = ["csr"] }
web-sys = { version = "0.3.69", features = ["CssStyleDeclaration", "DomTokenList", "HtmlSelectElement", "HtmlAudioElement", "DomRect", "Element", "HtmlAnchorElement", "FileReader", "Blob", "Document", "Element", "NodeList", "Window", "XmlHttpRequest", "DomParser", "SupportedType", "Performance", "PerformanceNavigation"] }
log = "0.4.21"
wasm-bindgen = "0.2.92"
yew-router = { version = "0.18.0" }
serde = { version = "1.0.197", features = ["derive"] }
gloo-net = "0.5.0"
gloo = "0.11.0"
anyhow = { version = "1.0.81", features = [] }
wasm-bindgen-futures = "0.4.42"
gloo-timers = { version = "0.3.0", features = ["futures"] }
base64 = "0.22.0"
yewdux = "0.10.0"
rss = "2.0.7"
chrono = "0.4.35"
serde_json = "1.0.125"
yewtil = "0.4.0"
gloo-utils = "0.2.0"
gloo-events = "0.2.0"
md5 = "0.7.0"
ammonia = "3.3.0"
pulldown-cmark = "0.10.0"
async-std = "1.12.0"
argon2 = "0.5.3"
rand = "0.8.5"
regex = "1.10.3"
js-sys = "0.3.68"
percent-encoding = "2.3.1"
data-encoding = "2.5.0"
url = "2.5.0"
serde-wasm-bindgen = "0.6.5"
chrono-tz = "0.9.0"
futures-util = "0.3.30"
gloo-file = "0.3.0"
async-trait = "0.1.80"